### ISSUE TITLE
Nagvis 1.8.2 is slow on large number of maps - no caching

### ISSUE THREAD

**Issue by li73772** [NagVis/nagvis#11]
I have generated a lot of maps (~6000). Each of them is small and would load in some msecs. But if I want to open one of the maps now, it still takes around 8 seconds until the map is starting to load. This time is used because the full page is generated each time, including the menu of all maps, macros, ... If I reduce the number of maps everything is fine, but I need them all.

Is there a way to enable some caching or using frames to prevent the generation of the map list for the header/menu bar each time ?

(This is not a new problem in 1.8.2 but also with other versions)

What I see during my investigations is, that there are two methods which try to get all maps, and they are not read from cache, but all read freshly from the disk again :-(
I have no idea if this is intention or not, but this might improve performance maybe a bit if caching could be used here as well ;)

Trace down the following lines of code :
NagvisHeaderMenu.php
        list($this->aMacros['maps'], $this->aMacros['permittedEditAnyMap']) = $this->getMapList('maps', $CORE->getAvailableMaps());
        $this->aMacros['mapNames'] = json_encode($CORE->getListMaps());

**Comment by LaMi-** [comment]
Wow, 6000 maps! This is a number of maps I never tested NagVis with. There might be serveral other issues in other places in such a this situation. e.g. in role permission configuration.

You have different options to improve this without changing the code:

a) you can disable the header menu either globally, per map by configuration
b) or you can just disable the header menu per call by adding the URL parameter &header_menu=0
c) Try adding show_in_lists=1 to the maps global sections to hide them from the overview page and header menu
d) Do you have header_show_states=1 set in global config? This will result in a lot of load during page rendering.

Regarding getMapList(). This function loads the global section of each map configuration, which is currently not using the map config cache. This could really be improved. 

I currently have no schedule/time to improve NagVis in this way. I might fix this one day, but can not promise if or when. But if you are interested, I can make you an offer for paid development request.

Otherwise, if you got any patches, I will review them, give feedback and maybe apply them to NagVis when they are sufficient.

**Comment by li73772** [comment]
Hi Lars,

thanks for the fast reply. 

Up to now it works without any problems (only the one mentioned is a problem in fact). Only 900 of the maps are shown in the menu in several groups. The rest is just used to drill down ...

The "show_in_list=0" does not help. It just hides the elements, but they are still loaded :-(
No, "header_show_states=1" kills the system with this number of maps and services. Which is ok.

I have added a badly implemented caching in CORE->getListMaps() which reduces the loading by 50%. So this is for me the right way to go. But I´m not sure what the consequences of my changes ...
I´m creating the list once in the beginning and then only remove all items where the permission is not there. Which is ok for me, in case of changes I have to remove the caching file at the moment as there is no check for validity of the cache

What is the price range for paid development by the way ? Just a rough number.

Gruß
Daniel

**Comment by li73772** [comment]
I´ve fixed it for me with some caching. Now it takes only some msecs until the loading of the real map starts. In which form shall I provide the code ? 
Sorry, but I never did that before.

**Comment by LaMi-** [comment]
I would need either a pull request (https://help.github.com/articles/using-pull-requests/) or at least a patch together with the information on which version the patch is based on.

**Comment by li73772** [comment]
Did a pull on two files GlobalCore.php and NagVisHeaderMenu.php hope this was ok. I´m happy to hear if this makes sense for you.

**Comment by LaMi-** [comment]
https://github.com/li73772/nagvis/commit/28f11ef5a530f5e506f002ae3ebcf7ed8932f801

**Comment by LaMi-** [comment]
I just applied your change to the master branch and changed some minor things. Thanks!

**Comment by fullmetalucard** [comment]
Hello,

I'm running nagvis-1.8rc3 and I am very interested about caching because I also have a hug amount of maps.
I tried to apply your patch, but it didn't worked for me. (downloaded the file and replaced the other one with it)
Updating the NagVisHeaderMenu.php file gives me that error:

`Error: (0) Object of class CoreUriHandler could not be converted to string (/data/nagvis-1.8rc3/share/frontend/nagvis-js/classes/NagVisHeaderMenu.php:40)

#0 /data/nagvis-1.8rc3/share/frontend/nagvis-js/classes/NagVisHeaderMenu.php(40): nagvisExceptionErrorHandler(4096, 'Object of class...', '/data/nagvis-1....', 40, Array)
#1 /data/nagvis-1.8rc3/share/frontend/nagvis-js/classes/FrontendModMap.php(110): NagVisHeaderMenu->__construct(Object(CoreUriHandler), 'default', Object(GlobalMapCfg))
#2 /data/nagvis-1.8rc3/share/frontend/nagvis-js/classes/FrontendModMap.php(80): FrontendModMap->showViewDialog()
#3 /data/nagvis-1.8rc3/share/server/core/functions/index.php(120): FrontendModMap->handleAction()
#4 /data/nagvis-1.8rc3/share/frontend/nagvis-js/index.php(56): require('/data/nagvis-1....')
#5 {main}`


Am I missing something? I didn't see any other file related to commit 28f11ef

Regards,

**Comment by LarsMichelsen** [comment]
just update to the latest 1.8 release.
