### ISSUE TITLE
"Clone Object" @ Geomap sometimes generate only long error

### ISSUE THREAD

**Issue by PepeOnAChair** [NagVis/nagvis#188]
Hello,
On Geomap (ver. 1.9.10), when I try to clone HostGroup object, sometimes it works normally and sometimes (with the same object) it does not work and outputs only error message - you can see it in the attachment.

I`ve found out that I can clone object but if I move it somewhere else on the map and than try to clone, it does not work.

If you need more details, please write me.

Thank you.
Pep.

![error printscreen](https://user-images.githubusercontent.com/19305232/57796927-95bcb100-7749-11e9-8f15-e172e1a3534d.JPG)
[error message.txt](https://github.com/NagVis/nagvis/files/3183795/error.message.txt)

**Comment by PepeOnAChair** [comment]
Here is a video I made, so I might be a bit more simple to debug that.
[clone bug video.zip](https://github.com/NagVis/nagvis/files/3282762/clone.bug.video.zip)
Thank you Pep.

**Comment by vpithart** [comment]
I'm going to fix this too and submit a pull request. Would you @LarsMichelsen allow me into maintainers here?

**Comment by vpithart** [comment]
The "clone object" feature is still buggy. After some 8 hours detangling the jungle of code, I've found the likely culprit:
https://github.com/NagVis/nagvis/blob/8a1054a8b925717e7cada31dfebfd51c3e3e1157/share/server/core/sources/worldmap.php#L327 

## Steps to reproduce
### STEP1 - display the map in browser (OK)
involves GET ... mod=Map&act=getMapObjects
The `process_worldmap()` correctly lists all ~20 objects according to `bbox`.
![image](https://user-images.githubusercontent.com/20604326/60609067-1d758200-9dc1-11e9-91cc-6cb13b407cd0.png)

### STEP2 - pick an object and clone it (OK)
involves GET ... mod=Map&act=addModify
The `process_worldmap()` isn't even fired because mapConfig is being read from cache (correct), and contains those ~20 objects (correct).

### STEP3 - relocate the object (not the clone) a few pixels away (OK)

### STEP4 - pick the same object and clone it (FAIL)
involves GET ... mod=Map&act=addModify
The `process_worldmap()` is being used because cache is no longer valid (correct). However the `bbox` is now missing, thus mapConfig gets empty.
![image](https://user-images.githubusercontent.com/20604326/60609494-1602a880-9dc2-11e9-9582-c863fba25170.png)
