### ISSUE TITLE
Host icon: Wrong number of services/wrong service states shown

### ISSUE THREAD

**Issue by Napsty** [NagVis/nagvis#37]
Using Nagvis 1.8.5 and Icinga 2.4.1 as backend (with livestatus). When I use the "Host Icon" on a map, it sometimes shows a critical icon although in Icinga I see that everything is OK on that particular host. When I hover over the map's icon, I see in the Summary Output that there are too many services:

    The Host is UP. Contains 32 OK, 8 CRITICAL, 2 UNKNOWN Services.

But this host only has 15 services.
When I manually refresh the icon, it changes back to the Host OK icon and in the summary output it says:

    The Host is UP. Contains 15 OK Services.

After a few seconds the wrong information comes back and the icon is changed to the critical host icon again.

On this map I have two hosts which have almost the same name. Let's call them host001 and host002. Interestingly on host002 there are currently 8 services critical and 2 unknown. So that would match for summary output above. However host001 shows the same critical icon as for host002. 
It seems that the host lookup in the backend gets confused, wrong regex maybe?

**Comment by LarsMichelsen** [comment]
If I remember correctly, this is a bug in Icinga2 which has been there for a longer time. Take a look at this ticket: https://dev.icinga.org/issues/7185

I see nothing NagVis can do about this at this point. It has to be fixed in the Livestatus implementation of Icinga2, sorry. Maybe you like to post your comment to the Icinga bug tracker which might bring it to the Icinga2 developers attention again.
