### ISSUE TITLE
PHP 7.0 NDO MySQL

### ISSUE THREAD

**Issue by Rico56890** [NagVis/nagvis#52]
**Info about my system:** 
Linux Ubuntu serveur 16.04 4.4.0-22-generic
Apache/2.4.18  -- PHP 7.0.4  -- MySQL 5.7.12  -- Nagvis 1.9b7 (2016-05-12)

**My problem:**
When i want to add host on map, i can't connect to backend and i have this error:

> Failed to get objects: {"message":"Your PHP installation lacks SQL support. You can not use the NDOMy Backend without php-mysql. (Backend-ID: ndomy_1)","title":"ERROR","type":"error"}

I already have installed php-mysql.
I can see on line 213 of _share/server/core/classes/GlobalBackendndomy.php_ file the checkMysqlSupport() function.

command `php -m` return modules _mysqli_ and _mysqlnd_. PHP7 removed _mysql_ API, leaving _mysqlnd_ and _mysqli_.
Is there the problem source ?

**Comment by LarsMichelsen** [comment]
I recommend using the MKLivestatus backend instead of the NDO MySQL backend. It is performing better and used by a lot more users.

However, it should not be too hard to make the existing code which uses the php mysql_* functions be able to work with mysqli_*, but I currently don't have a NDO + MySQL setup and can not test those changes.

**Comment by SteScho** [comment]
I have fixed that problem for ndo/ido here on my site. It is also possible to use the sql-mode ONLY_FULL_GROUP_BY in the new mysql versions. See pull request #85

**Comment by LarsMichelsen** [comment]
Thanks! The pull request has been merged.
