### ISSUE TITLE
Exception Errors are ignoring display_errors settings

### ISSUE THREAD

**Issue by davebo** [NagVis/nagvis#6]
I am getting displayed php exceptions with display_errors = Off and display_startup_errors = Off set in php.ini .  If I disable the nagvisExceptionErrorHandler (by commenting out set_error_handler in navisErrorHandler.php) the php display settings are honored and the php error is not displayed.

**Comment by LaMi-** [comment]
Which php errors? There should not be a single one so if you get one. If you get one, this should be an error which really should be handled correctly instead of just "turn all errors of".

**Comment by davebo** [comment]
well, what happens is I'm using nagiosbp backend and configurations are not keeping up with nagios alert changes.  When the nagios configs no longer match the nagiosbp/nagvis configs, errors are thrown.  Not having a page load properly for a short time (until the configs are fixed) is much, much better than a giant php red box.

**Comment by LaMi-** [comment]
Would you send me the exact error? Maybe I can fix the error handling here.

**Comment by davebo** [comment]
Well, any error will do.  I have a development server where I want to see errors visually (the big red box) and I have a production server where errors should only be written to the log (no big red box, ever).  You can test this by throwing an exception in any page.  As I understand it,  visual error reporting is disabled in php by default.
```
display_errors = Off
display_startup_errors = Off
```
With the current error handler, errors are always displayed visually, irregardless of php settings.

btw - NagVis is really, really cool stuff!  thank you for all the work you've put into it !!

**Comment by LaMi-** [comment]
My point is: If an error occures within NagVis it is mostly an error which should be shown to the user, because it might affect the shown data, that the data is - for example - outdated. Depending on the type of the error, they should be handled in a different way.

For example the error you described, that single NagiosBP objects can not be updated is handled wrong. Instead of the red box popping up, only the affected objects should change their states to the blue "ERROR" icon and showing the reason for the error in the object state output.

Other errors which prevent the map state from being updated shold be shown up as big red box to show the user that he can not rely on the shown states.

In NagVis there should not be any exception or error reaching the red box, except when it is a problem we want to show to the user. I don't want to suppress "all possible exceptions" with options like the php error reporting options.

This is the reason why I asked you for the excact error / exception you see. Just to fix the handling of these errors.

**Comment by davebo** [comment]
I've added '& FOO' to an existing nagiosbp definition, ( FOO is not defined ) and get this popup error:

Error: (0) Undefined offset: 3 (/etc/nagvis/share/server/core/functions/core.php:123)

#0 /etc/nagvis/share/server/core/functions/core.php(123): nagvisExceptionErrorHandler(8, 'Undefined offse...', '/etc/nagvis/sha...', 123, Array)
#1 /etc/nagvis/share/server/core/classes/GlobalBackendnagiosbp.php(178): state_num(3)
#2 /etc/nagvis/share/server/core/classes/GlobalBackendnagiosbp.php(213): GlobalBackendnagiosbp->getBPState(NULL)
#3 /etc/nagvis/share/server/core/classes/GlobalBackendnagiosbp.php(265): GlobalBackendnagiosbp->getBPCounts(Array)
#4 /etc/nagvis/share/server/core/classes/CoreBackendMgmt.php(449): GlobalBackendnagiosbp->getServicegroupStateCounts(Array, 2, Array)
#5 /etc/nagvis/share/server/core/classes/CoreBackendMgmt.php(169): CoreBackendMgmt->fetchStateCounts('nagiosbpprod', 'servicegroupMem...', 2, Array)
#6 /etc/nagvis/share/server/core/classes/NagVisMap.php(54): CoreBackendMgmt->execute()
#7 /etc/nagvis/share/server/core/classes/CoreModMap.php(808): NagVisMap->__construct(Object(GlobalMapCfg), true, true)
#8 /etc/nagvis/share/server/core/classes/CoreModMap.php(106): CoreModMap->getMapObjects()
#9 /etc/nagvis/share/server/core/functions/index.php(120): CoreModMap->handleAction()
#10 /etc/nagvis/share/server/core/ajax_handler.php(63): require('/etc/nagvis/sha...')
#11 {main}
