### ISSUE TITLE
Users can edit "no permission" object in worldmap

### ISSUE THREAD

**Issue by white-line** [NagVis/nagvis#75]
Example:
- Create user 'test';
- Create two worldmaps - worldmap1 and worldmap2
- Create role 'test' with rights "view, edit" to worldmap1 and only "view" to worldmap2

If user open worldmap1 - he can see other objects from worldmap2 , and if he click 'modify', this action do acces for his.

**Comment by white-line** [comment]
### Unlike worldmap.db
 Maybe write/read host data out 'maps/map.cfg' ? This as a solution for this problem.

**Comment by white-line** [comment]
Or create new worldmap.db for every map. Example:

./maps/map1.cfg
./maps/map1.worldmap.db

**Comment by LarsMichelsen** [comment]
The worldmap makes the objects visible on the map that you can see according to the core. These are the ones that you are a contact for. In case an object you are permitted to see has a position stored on one worldmap, you will see it on other worldmaps on the same possition.

This is by design. At the moment there is no option to change this by configuration.
