### ISSUE TITLE
Javascript error with long lines on worldmap

### ISSUE THREAD

**Issue by white-line** [NagVis/nagvis#78]
Error message:

Javascript error occured: TypeError: this.objects[parentObjId] is undefined 

---

nagvis 1.9.b9

I take this error if I create line, example out Washington City to New York City, and after zoom map for Washington, where zoom value == 15 ( OpenStreetMap )

**Comment by LarsMichelsen** [comment]
I just fixed the "TypeError: this.objects[parentObjId] is undefined" issue. So this error should not be shown anymore for this situation from next nightly builds.

But now the line may be hidden when zooming in. This is related to the maximum canvas element size of the browsers (http://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element).

The problem here is that the line parts out of the screen are rendered with their full dimension reaching a very large canvas size.

We would have to render only the visible part and calculate the coordinates correctly. Currently I don't want to make such a change.
